//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApplication1.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Get_InfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Obtener_TodoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Insertar_nuevoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarOperationCompleted;
        
        private System.Threading.SendOrPostCallback cuenta_registrosOperationCompleted;
        
        private System.Threading.SendOrPostCallback Borra_RegistroOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::WindowsFormsApplication1.Properties.Settings.Default.WindowsFormsApplication1_localhost_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Get_InfoCompletedEventHandler Get_InfoCompleted;
        
        /// <remarks/>
        public event Obtener_TodoCompletedEventHandler Obtener_TodoCompleted;
        
        /// <remarks/>
        public event Insertar_nuevoCompletedEventHandler Insertar_nuevoCompleted;
        
        /// <remarks/>
        public event ActualizarCompletedEventHandler ActualizarCompleted;
        
        /// <remarks/>
        public event cuenta_registrosCompletedEventHandler cuenta_registrosCompleted;
        
        /// <remarks/>
        public event Borra_RegistroCompletedEventHandler Borra_RegistroCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Get_Info", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Get_Info(string nombre) {
            object[] results = this.Invoke("Get_Info", new object[] {
                        nombre});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Get_InfoAsync(string nombre) {
            this.Get_InfoAsync(nombre, null);
        }
        
        /// <remarks/>
        public void Get_InfoAsync(string nombre, object userState) {
            if ((this.Get_InfoOperationCompleted == null)) {
                this.Get_InfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGet_InfoOperationCompleted);
            }
            this.InvokeAsync("Get_Info", new object[] {
                        nombre}, this.Get_InfoOperationCompleted, userState);
        }
        
        private void OnGet_InfoOperationCompleted(object arg) {
            if ((this.Get_InfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Get_InfoCompleted(this, new Get_InfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Obtener_Todo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Obtener_Todo() {
            object[] results = this.Invoke("Obtener_Todo", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Obtener_TodoAsync() {
            this.Obtener_TodoAsync(null);
        }
        
        /// <remarks/>
        public void Obtener_TodoAsync(object userState) {
            if ((this.Obtener_TodoOperationCompleted == null)) {
                this.Obtener_TodoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtener_TodoOperationCompleted);
            }
            this.InvokeAsync("Obtener_Todo", new object[0], this.Obtener_TodoOperationCompleted, userState);
        }
        
        private void OnObtener_TodoOperationCompleted(object arg) {
            if ((this.Obtener_TodoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Obtener_TodoCompleted(this, new Obtener_TodoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insertar_nuevo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Insertar_nuevo(string matricula, string nombre, string p_apellido, string s_apellido, string fecha_ingreso, string plantel, string carrera, string semestre, string direccion, string correo, string telefono) {
            object[] results = this.Invoke("Insertar_nuevo", new object[] {
                        matricula,
                        nombre,
                        p_apellido,
                        s_apellido,
                        fecha_ingreso,
                        plantel,
                        carrera,
                        semestre,
                        direccion,
                        correo,
                        telefono});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Insertar_nuevoAsync(string matricula, string nombre, string p_apellido, string s_apellido, string fecha_ingreso, string plantel, string carrera, string semestre, string direccion, string correo, string telefono) {
            this.Insertar_nuevoAsync(matricula, nombre, p_apellido, s_apellido, fecha_ingreso, plantel, carrera, semestre, direccion, correo, telefono, null);
        }
        
        /// <remarks/>
        public void Insertar_nuevoAsync(string matricula, string nombre, string p_apellido, string s_apellido, string fecha_ingreso, string plantel, string carrera, string semestre, string direccion, string correo, string telefono, object userState) {
            if ((this.Insertar_nuevoOperationCompleted == null)) {
                this.Insertar_nuevoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertar_nuevoOperationCompleted);
            }
            this.InvokeAsync("Insertar_nuevo", new object[] {
                        matricula,
                        nombre,
                        p_apellido,
                        s_apellido,
                        fecha_ingreso,
                        plantel,
                        carrera,
                        semestre,
                        direccion,
                        correo,
                        telefono}, this.Insertar_nuevoOperationCompleted, userState);
        }
        
        private void OnInsertar_nuevoOperationCompleted(object arg) {
            if ((this.Insertar_nuevoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Insertar_nuevoCompleted(this, new Insertar_nuevoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Actualizar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Actualizar(string matricula, string nombre, string p_apellido, string s_apellido, string fecha_ingreso, string plantel, string carrera, string semestre, string direccion, string correo, string telefono) {
            object[] results = this.Invoke("Actualizar", new object[] {
                        matricula,
                        nombre,
                        p_apellido,
                        s_apellido,
                        fecha_ingreso,
                        plantel,
                        carrera,
                        semestre,
                        direccion,
                        correo,
                        telefono});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarAsync(string matricula, string nombre, string p_apellido, string s_apellido, string fecha_ingreso, string plantel, string carrera, string semestre, string direccion, string correo, string telefono) {
            this.ActualizarAsync(matricula, nombre, p_apellido, s_apellido, fecha_ingreso, plantel, carrera, semestre, direccion, correo, telefono, null);
        }
        
        /// <remarks/>
        public void ActualizarAsync(string matricula, string nombre, string p_apellido, string s_apellido, string fecha_ingreso, string plantel, string carrera, string semestre, string direccion, string correo, string telefono, object userState) {
            if ((this.ActualizarOperationCompleted == null)) {
                this.ActualizarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarOperationCompleted);
            }
            this.InvokeAsync("Actualizar", new object[] {
                        matricula,
                        nombre,
                        p_apellido,
                        s_apellido,
                        fecha_ingreso,
                        plantel,
                        carrera,
                        semestre,
                        direccion,
                        correo,
                        telefono}, this.ActualizarOperationCompleted, userState);
        }
        
        private void OnActualizarOperationCompleted(object arg) {
            if ((this.ActualizarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarCompleted(this, new ActualizarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cuenta_registros", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string cuenta_registros() {
            object[] results = this.Invoke("cuenta_registros", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cuenta_registrosAsync() {
            this.cuenta_registrosAsync(null);
        }
        
        /// <remarks/>
        public void cuenta_registrosAsync(object userState) {
            if ((this.cuenta_registrosOperationCompleted == null)) {
                this.cuenta_registrosOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncuenta_registrosOperationCompleted);
            }
            this.InvokeAsync("cuenta_registros", new object[0], this.cuenta_registrosOperationCompleted, userState);
        }
        
        private void Oncuenta_registrosOperationCompleted(object arg) {
            if ((this.cuenta_registrosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cuenta_registrosCompleted(this, new cuenta_registrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Borra_Registro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Borra_Registro(string matricula) {
            object[] results = this.Invoke("Borra_Registro", new object[] {
                        matricula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Borra_RegistroAsync(string matricula) {
            this.Borra_RegistroAsync(matricula, null);
        }
        
        /// <remarks/>
        public void Borra_RegistroAsync(string matricula, object userState) {
            if ((this.Borra_RegistroOperationCompleted == null)) {
                this.Borra_RegistroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBorra_RegistroOperationCompleted);
            }
            this.InvokeAsync("Borra_Registro", new object[] {
                        matricula}, this.Borra_RegistroOperationCompleted, userState);
        }
        
        private void OnBorra_RegistroOperationCompleted(object arg) {
            if ((this.Borra_RegistroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Borra_RegistroCompleted(this, new Borra_RegistroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Get_InfoCompletedEventHandler(object sender, Get_InfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Get_InfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Get_InfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Obtener_TodoCompletedEventHandler(object sender, Obtener_TodoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Obtener_TodoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Obtener_TodoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Insertar_nuevoCompletedEventHandler(object sender, Insertar_nuevoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Insertar_nuevoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Insertar_nuevoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ActualizarCompletedEventHandler(object sender, ActualizarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void cuenta_registrosCompletedEventHandler(object sender, cuenta_registrosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cuenta_registrosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cuenta_registrosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Borra_RegistroCompletedEventHandler(object sender, Borra_RegistroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Borra_RegistroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Borra_RegistroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591